### ISSUE TITLE
Error 503

### ISSUE THREAD

**Issue by Felli** [saturngod/BanEmail#1]
This plugin causes an Error 503 if installed and enabled.

**Comment by saturngod** [comment]
May I know what version of esoTalk are you using ? I am using on 1.0.0g5 and it is working fine.

**Comment by Felli** [comment]
I'm using the most stable version which is g4.

**Comment by saturngod** [comment]
Tested on g4 and working fine. 
Error 503 may not related with the plugin. It may be problem of esotalk or your web server.

**Comment by saturngod** [comment]
Can you check the web server error log or try to enable the debug mode in esotalk for checking error.

I tested with Apache and Nginx , there is no problem.

**Comment by Felli** [comment]
I found the problem, it was a plugin that I was beta testing that was interfering with your's.
